import { attribute, autoGeneratedHashKey, table} from '@aws/dynamodb-data-mapper-annotations';
import { Publication } from './Publication';
import { UserProfileInfo } from './UserProfileInfo';

@table("BlogPost")
export class BlogPost{
    @autoGeneratedHashKey()
    Id: string
    @attribute()
    Author: UserProfileInfo
    @attribute()
    Title: string
    @attribute()
    Publication?: Publication
    @attribute()
    Tags?: string[]
    @attribute()
    Content: string //(Markdown)
    @attribute()
    CreatedAt: string //DateTime
    @attribute()
    LastUpdated?: string //DateTime
    @attribute()
    Likes: string[] //List of User Names
    @attribute()
    Pick?: string //(Features/Editor Pick/None)

}
