import { attribute, autoGeneratedHashKey, table } from "@aws/dynamodb-data-mapper-annotations"
import { UserProfileInfo } from "./UserProfileInfo"

@table("BlogPostComments")
export class BlogPostComments{
    @autoGeneratedHashKey()
    Id: string 
    @attribute()
    Author: UserProfileInfo
    @attribute()
    Content: string 
    @attribute()
    CreatedAt: string //DateTime
    @attribute()
    Likes?: string[] //List of User Names
    @attribute()
    ReplyComments?: BlogPostComments[] 
}