import { attribute, autoGeneratedHashKey } from "@aws/dynamodb-data-mapper-annotations"
import { BlogPost } from "./BlogPost"
import { UserProfileInfo } from "./UserProfileInfo"

export class Publication{
    @autoGeneratedHashKey()
    Id: string
    @attribute()
    Name: string
    @attribute()
    Owner: UserProfileInfo[] //Each Owner must be a User
    @attribute()
    Editors: UserProfileInfo[] //Each Editor must be a User
    @attribute()
    Blogs: BlogPost
}