import { attribute, autoGeneratedHashKey } from "@aws/dynamodb-data-mapper-annotations"
import { Publication } from "./Publication"
import { UserProfileInfo } from "./UserProfileInfo"

export class User{
    @autoGeneratedHashKey()
    Id: string
    @attribute()
    Username: string
    @attribute()
    Fullname: string
    @attribute()
    Email: string
    @attribute()
    DisplayPictureURL?: string
    @attribute()
    Title?: string
    @attribute()
    Bio?: string
    @attribute()
    PasswordHash: string
    @attribute()
    Notifications?: boolean //(On/Off)
    @attribute()
    LastActive?: string //(preference of user)
    @attribute()
    FollowerUsers?: UserProfileInfo[] //detailed profile 
    @attribute()
    FollowingUsers?: UserProfileInfo[] //detailed profile
    @attribute()
    FollowingPublications?: Publication[] //detailed profile
    @attribute()
    EditingPublications?: Publication[] //detailed profile 

}